[package]
edition = "2018"
name = "rusty-journal"
version = "0.1.0"
[dependencies]
anyhow = "*"
home = "*"
serde_json = "*"
structopt = "0.3"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.serde]
features = ["derive"]
version = "1.0"
